package com.example.MessageMemo;

import java.sql.Timestamp;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
//import com.example.MysqlAccess.Customer;
//import com.example.MysqlAccess.CustomerRepository;
//import com.example.MysqlAccess.EmployeeRepository;

@Controller
public class MessageMemoController {
	@Autowired	// This means to get the bean called CustomerRepository
	// Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;
    @Autowired
	private EmployeeRepository employeeRepository;
    @Autowired
    private MessageMemoRepository messageMemoRepository;
	
	@RequestMapping("/msgmemo/inputForm")
    public String index(Model model) {
		
		// M_CUSTOMERテーブルの全データを取得
		Iterable<Customer> customerList = customerRepository.findAll();
		Iterable<Employee> employeeList = employeeRepository.findAll();
				
		// モデルに属性追加
		model.addAttribute("customerlist",customerList);
		model.addAttribute("employeelist",employeeList);
		
		// DBアクセスTop画面を表示
        return "insertMessageMemo";
    }
	
//	登録処理
	@PostMapping(path="inputForm")
	public @ResponseBody String addNewMessageMemo(	  @RequestParam String to_name
													, @RequestParam String receiver_cd
													, @RequestParam Timestamp receiv_time
													, @RequestParam String custmer_cd
													, @RequestParam String sender
													, @RequestParam String message_cd
													, @RequestParam String memo){

		Message messageMemoAddData = new Message();
		
		int count = rep.countT_message();
		int m_num;
		if(count == 0) {
			m_num = 1;
		}else {
			m_num = count + 1;
		}
		
		messageMemoAddData.setAll(m_num,to_name, receiver_cd, receiv_time, custmer_cd, sender, message_cd, memo);
		
		Timestamp timestamp = new Timestamp(System.currentTimeMillis());
		messageMemoAddData.setUpdate_date(timestamp);
		messageMemoAddData.setUpdate_user("springuser");
		messageMemoAddData.setCreate_date(timestamp);
		messageMemoAddData.setCreate_user("springuser");
		
		messageMemoRepository.save(messageMemoAddData);
		
		return "insertMessageMemo.html";
	}
}